"""
Unreal Editor automation for SelfEngineBridge.json.

Run through UnrealEditor-Cmd.exe with:
  -ExecutePythonScript=".../tools/unreal/selfengine_bridge_export.py --manifest D:/UEProject/.../SelfEngineBridge.json"

This script intentionally complements the inventory manifest generated by
scripts/Generate-SelfEngineBridgeManifest.ps1. It runs inside UE, opens each map,
enumerates actors/components/lights/cameras/post-process volumes, and writes the
scene metadata back into the same bridge manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import sys
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Optional, Tuple

import unreal  # type: ignore


def _log(message: str) -> None:
    unreal.log("[SelfEngineBridge] " + message)


def _warn(message: str) -> None:
    unreal.log_warning("[SelfEngineBridge] " + message)


def _error(message: str) -> None:
    unreal.log_error("[SelfEngineBridge] " + message)


def _vector(value: Any) -> List[float]:
    return [
        float(getattr(value, "x", 0.0)),
        float(getattr(value, "y", 0.0)),
        float(getattr(value, "z", 0.0)),
    ]


def _rotator(value: Any) -> List[float]:
    return [
        float(getattr(value, "pitch", 0.0)),
        float(getattr(value, "yaw", 0.0)),
        float(getattr(value, "roll", 0.0)),
    ]


def _color(value: Any) -> List[float]:
    return [
        float(getattr(value, "r", 1.0)),
        float(getattr(value, "g", 1.0)),
        float(getattr(value, "b", 1.0)),
        float(getattr(value, "a", 1.0)),
    ]


def _vec_add(a: List[float], b: List[float]) -> List[float]:
    return [a[0] + b[0], a[1] + b[1], a[2] + b[2]]


def _vec_sub(a: List[float], b: List[float]) -> List[float]:
    return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]


def _vec_mul(value: List[float], scalar: float) -> List[float]:
    return [value[0] * scalar, value[1] * scalar, value[2] * scalar]


def _vec_length(value: List[float]) -> float:
    return math.sqrt(value[0] * value[0] + value[1] * value[1] + value[2] * value[2])


def _vec_normalize(value: List[float], fallback: List[float]) -> List[float]:
    length = _vec_length(value)
    if length <= 0.0001:
        return fallback
    return [value[0] / length, value[1] / length, value[2] / length]


def _vec_mid(a: List[float], b: List[float]) -> List[float]:
    return [(a[0] + b[0]) * 0.5, (a[1] + b[1]) * 0.5, (a[2] + b[2]) * 0.5]


def _asset_path(value: Any) -> str:
    if value is None:
        return ""
    try:
        return str(value.get_path_name())
    except Exception:
        return str(value)


def _class_name(value: Any) -> str:
    try:
        return str(value.get_class().get_name())
    except Exception:
        return value.__class__.__name__


def _actor_label(actor: Any) -> str:
    try:
        return str(actor.get_actor_label())
    except Exception:
        try:
            return str(actor.get_name())
        except Exception:
            return ""


def _safe_editor_property(obj: Any, name: str, default: Any = None) -> Any:
    try:
        return obj.get_editor_property(name)
    except Exception:
        return default


def _set_editor_property(obj: Any, name: str, value: Any) -> bool:
    try:
        setattr(obj, name, value)
        return True
    except Exception:
        pass
    try:
        obj.set_editor_property(name, value)
        return True
    except Exception:
        return False


def _safe_file_stem(source_asset_id: str) -> str:
    text = source_asset_id.strip() or "unnamed_asset"
    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", text.strip("/").replace("/", "_"))
    cleaned = cleaned.strip("._-") or "unnamed_asset"
    if len(cleaned) > 96:
        cleaned = cleaned[-96:]
    return f"{cleaned}_{digest}"


def _asset_class_is_mesh(asset: Any) -> bool:
    class_name = _class_name(asset)
    return "StaticMesh" in class_name or "SkeletalMesh" in class_name


def _default_export_root(manifest_path: str, manifest: Dict[str, Any]) -> str:
    manifest_root = str(manifest.get("exportedRootPath") or "")
    if manifest_root:
        return os.path.abspath(manifest_root)

    project_root = str(manifest.get("projectRootPath") or "")
    if project_root:
        return os.path.abspath(os.path.join(project_root, "Saved", "SelfEngineBridge", "Exported"))

    return os.path.abspath(os.path.join(os.path.dirname(manifest_path), "Saved", "SelfEngineBridge", "Exported"))


def _create_fbx_export_options() -> Optional[Any]:
    try:
        options = unreal.FbxExportOption()
        _set_editor_property(options, "ascii", False)
        _set_editor_property(options, "collision", False)
        _set_editor_property(options, "level_of_detail", True)
        return options
    except Exception:
        return None


def _run_asset_export_task(asset: Any, output_path: str) -> Tuple[bool, str]:
    task = unreal.AssetExportTask()
    _set_editor_property(task, "object", asset)
    _set_editor_property(task, "filename", output_path)
    _set_editor_property(task, "automated", True)
    _set_editor_property(task, "prompt", False)
    _set_editor_property(task, "replace_identical", True)
    _set_editor_property(task, "write_empty_files", False)
    options = _create_fbx_export_options()
    if options is not None:
        _set_editor_property(task, "options", options)

    try:
        result = bool(unreal.Exporter.run_asset_export_task(task))
    except Exception as exc:
        return False, f"AssetExportTask failed: {exc}"

    if not result:
        return False, "AssetExportTask returned false"
    if not os.path.isfile(output_path):
        return False, "AssetExportTask reported success but no file was written"

    return True, ""


def _export_mesh_asset(source_mesh: Any, context: Dict[str, Any]) -> Dict[str, Any]:
    source_asset_id = _asset_path(source_mesh)
    if not source_asset_id:
        return {
            "sourceAssetId": "",
            "plannedExportedPath": "",
            "exportedPath": "",
            "exportStatus": "missing_source_mesh",
            "exportFormat": "fbx",
            "message": "Component had no source mesh asset.",
        }

    cache: Dict[str, Dict[str, Any]] = context["mesh_export_cache"]
    cached = cache.get(source_asset_id)
    if cached is not None:
        return cached

    output_path = os.path.join(
        context["mesh_export_root"],
        _safe_file_stem(source_asset_id) + ".fbx",
    )
    record: Dict[str, Any] = {
        "sourceAssetId": source_asset_id,
        "sourceAssetClass": _class_name(source_mesh),
        "plannedExportedPath": output_path,
        "exportedPath": "",
        "exportStatus": "requires_mesh_export",
        "exportFormat": "fbx",
        "message": "",
    }
    cache[source_asset_id] = record

    if not context["export_meshes"]:
        record["message"] = "Mesh export disabled by --no-mesh-export."
        return record

    if not _asset_class_is_mesh(source_mesh):
        record["exportStatus"] = "unsupported_mesh_asset_class"
        record["message"] = f"Unsupported source asset class: {_class_name(source_mesh)}"
        return record

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    if os.path.isfile(output_path) and not context["force_mesh_export"]:
        record["exportedPath"] = output_path
        record["exportStatus"] = "exported_existing"
        return record

    ok, message = _run_asset_export_task(source_mesh, output_path)
    if ok:
        record["exportedPath"] = output_path
        record["exportStatus"] = "exported"
        return record

    record["exportStatus"] = "mesh_export_failed"
    record["message"] = message
    _warn(f"Mesh export failed for {source_asset_id}: {message}")
    return record


def _component_world_transform(component: Any) -> Dict[str, List[float]]:
    transform = component.get_world_transform()
    record = {
        "position": _vector(transform.translation),
        "rotationDegrees": _rotator(transform.rotation.rotator()),
        "scale": _vector(transform.scale3d),
    }
    try:
        record["forward"] = _vector(transform.get_unit_axis(unreal.Axis.X))
        record["right"] = _vector(transform.get_unit_axis(unreal.Axis.Y))
        record["up"] = _vector(transform.get_unit_axis(unreal.Axis.Z))
    except Exception:
        pass

    return record


def _actor_record(actor: Any) -> Dict[str, Any]:
    transform = actor.get_actor_transform()
    transform_record = {
        "position": _vector(transform.translation),
        "rotationDegrees": _rotator(transform.rotation.rotator()),
        "scale": _vector(transform.scale3d),
    }
    try:
        transform_record["forward"] = _vector(transform.get_unit_axis(unreal.Axis.X))
        transform_record["right"] = _vector(transform.get_unit_axis(unreal.Axis.Y))
        transform_record["up"] = _vector(transform.get_unit_axis(unreal.Axis.Z))
    except Exception:
        pass

    return {
        "id": actor.get_path_name(),
        "name": _actor_label(actor),
        "class": _class_name(actor),
        "path": actor.get_path_name(),
        "transform": transform_record,
    }


def _mesh_component_record(
    actor: Any,
    component: Any,
    context: Dict[str, Any]
) -> Optional[Dict[str, Any]]:
    mesh = _safe_editor_property(component, "static_mesh")
    skeletal_mesh = _safe_editor_property(component, "skeletal_mesh")
    source_mesh = mesh if mesh is not None else skeletal_mesh
    if source_mesh is None:
        return None

    materials: List[str] = []
    try:
        material_count = int(component.get_num_materials())
        for index in range(material_count):
            material = component.get_material(index)
            materials.append(_asset_path(material))
    except Exception:
        pass

    bounds = {}
    try:
        origin, extent = component.get_local_bounds()
        bounds = {
            "localMin": _vector(origin),
            "localMax": _vector(extent),
        }
    except Exception:
        pass

    source_asset_id = _asset_path(source_mesh)
    export_record = _export_mesh_asset(source_mesh, context)

    return {
        "id": component.get_path_name(),
        "actorId": actor.get_path_name(),
        "actorName": _actor_label(actor),
        "componentName": component.get_name(),
        "componentClass": _class_name(component),
        "sourceAssetId": source_asset_id,
        "sourceAssetClass": _class_name(source_mesh),
        "materials": materials,
        "transform": _component_world_transform(component),
        "bounds": bounds,
        "exportedPath": export_record.get("exportedPath", ""),
        "plannedExportedPath": export_record.get("plannedExportedPath", ""),
        "exportStatus": export_record.get("exportStatus", "requires_mesh_export"),
        "exportFormat": export_record.get("exportFormat", "fbx"),
        "exportMessage": export_record.get("message", ""),
    }


def _light_component_record(actor: Any, component: Any) -> Optional[Dict[str, Any]]:
    class_name = _class_name(component)
    if "LightComponent" not in class_name and not class_name.endswith("LightComponent"):
        return None

    return {
        "id": component.get_path_name(),
        "actorId": actor.get_path_name(),
        "actorName": _actor_label(actor),
        "componentName": component.get_name(),
        "componentClass": class_name,
        "transform": _component_world_transform(component),
        "intensity": float(_safe_editor_property(component, "intensity", 0.0) or 0.0),
        "lightColor": _color(_safe_editor_property(component, "light_color", None)),
        "attenuationRadius": float(_safe_editor_property(component, "attenuation_radius", 0.0) or 0.0),
        "sourceRadius": float(_safe_editor_property(component, "source_radius", 0.0) or 0.0),
        "innerConeAngle": float(_safe_editor_property(component, "inner_cone_angle", 0.0) or 0.0),
        "outerConeAngle": float(_safe_editor_property(component, "outer_cone_angle", 0.0) or 0.0),
    }


def _camera_component_record(actor: Any, component: Any) -> Optional[Dict[str, Any]]:
    class_name = _class_name(component)
    if "CameraComponent" not in class_name:
        return None

    return {
        "id": component.get_path_name(),
        "actorId": actor.get_path_name(),
        "actorName": _actor_label(actor),
        "componentName": component.get_name(),
        "componentClass": class_name,
        "transform": _component_world_transform(component),
        "fieldOfView": float(_safe_editor_property(component, "field_of_view", 0.0) or 0.0),
        "aspectRatio": float(_safe_editor_property(component, "aspect_ratio", 0.0) or 0.0),
        "nearClipPlane": float(_safe_editor_property(component, "near_clip_plane", 0.0) or 0.0),
    }


def _component_world_bounds(component: Any) -> Optional[Tuple[List[float], List[float]]]:
    try:
        box = component.bounds.get_box()
        minimum = _vector(box.min)
        maximum = _vector(box.max)
        if max(abs(maximum[index] - minimum[index]) for index in range(3)) > 0.1:
            return minimum, maximum
    except Exception:
        pass

    try:
        origin = component.bounds.origin
        extent = component.bounds.box_extent
        minimum = [
            float(getattr(origin, "x", 0.0)) - float(getattr(extent, "x", 0.0)),
            float(getattr(origin, "y", 0.0)) - float(getattr(extent, "y", 0.0)),
            float(getattr(origin, "z", 0.0)) - float(getattr(extent, "z", 0.0)),
        ]
        maximum = [
            float(getattr(origin, "x", 0.0)) + float(getattr(extent, "x", 0.0)),
            float(getattr(origin, "y", 0.0)) + float(getattr(extent, "y", 0.0)),
            float(getattr(origin, "z", 0.0)) + float(getattr(extent, "z", 0.0)),
        ]
        if max(abs(maximum[index] - minimum[index]) for index in range(3)) > 0.1:
            return minimum, maximum
    except Exception:
        pass

    try:
        origin, extent = component.get_local_bounds()
        transform = component.get_world_transform()
        corners: List[List[float]] = []
        for x_sign in (-1.0, 1.0):
            for y_sign in (-1.0, 1.0):
                for z_sign in (-1.0, 1.0):
                    local = unreal.Vector(
                        float(getattr(origin, "x", 0.0)) + float(getattr(extent, "x", 0.0)) * x_sign,
                        float(getattr(origin, "y", 0.0)) + float(getattr(extent, "y", 0.0)) * y_sign,
                        float(getattr(origin, "z", 0.0)) + float(getattr(extent, "z", 0.0)) * z_sign,
                    )
                    world = transform.transform_position(local)
                    corners.append(_vector(world))
        return (
            [min(corner[index] for corner in corners) for index in range(3)],
            [max(corner[index] for corner in corners) for index in range(3)],
        )
    except Exception:
        return None


def _mesh_component_bounds_for_camera(
    component: Any,
    source_asset_id: str,
    mesh_record: Dict[str, Any]
) -> Optional[Tuple[List[float], List[float]]]:
    if "SkySphere" in source_asset_id or "EngineSky" in source_asset_id:
        return None

    bounds = _component_world_bounds(component)
    if bounds is None:
        local_bounds = mesh_record.get("bounds") or {}
        transform = mesh_record.get("transform") or {}
        local_min = local_bounds.get("localMin")
        local_max = local_bounds.get("localMax")
        position = transform.get("position")
        scale = transform.get("scale")
        if (
            isinstance(local_min, list) and len(local_min) >= 3 and
            isinstance(local_max, list) and len(local_max) >= 3 and
            isinstance(position, list) and len(position) >= 3 and
            isinstance(scale, list) and len(scale) >= 3
        ):
            minimum = [
                float(position[index]) + min(float(local_min[index]) * float(scale[index]), float(local_max[index]) * float(scale[index]))
                for index in range(3)
            ]
            maximum = [
                float(position[index]) + max(float(local_min[index]) * float(scale[index]), float(local_max[index]) * float(scale[index]))
                for index in range(3)
            ]
            bounds = (minimum, maximum)
        else:
            return None

    minimum, maximum = bounds
    extent = _vec_mul(_vec_sub(maximum, minimum), 0.5)
    if max(abs(extent[0]), abs(extent[1]), abs(extent[2])) <= 0.1:
        return None
    return bounds


def _merge_bounds(
    current: Optional[Tuple[List[float], List[float]]],
    candidate: Tuple[List[float], List[float]]
) -> Tuple[List[float], List[float]]:
    if current is None:
        return ([candidate[0][0], candidate[0][1], candidate[0][2]], [candidate[1][0], candidate[1][1], candidate[1][2]])
    return (
        [min(current[0][index], candidate[0][index]) for index in range(3)],
        [max(current[1][index], candidate[1][index]) for index in range(3)],
    )


def _generated_reference_camera_record(
    scene: Dict[str, Any],
    mesh_bounds: Optional[Tuple[List[float], List[float]]],
    fallback_location: List[float]
) -> Dict[str, Any]:
    if mesh_bounds is not None:
        minimum, maximum = mesh_bounds
        center = _vec_mid(minimum, maximum)
        extent = _vec_mul(_vec_sub(maximum, minimum), 0.5)
        radius = max(_vec_length(extent), 250.0)
    else:
        center = fallback_location
        radius = 1000.0

    view_direction = _vec_normalize([-0.62, -0.56, -0.55], [-1.0, -0.35, -0.35])
    distance = max(radius * 2.7, 900.0)
    position = _vec_sub(center, _vec_mul(view_direction, distance))
    position[2] += max(radius * 0.35, 180.0)
    forward = _vec_normalize(_vec_sub(center, position), view_direction)
    up = [0.0, 0.0, 1.0]

    record = {
        "id": f"{scene.get('id', 'scene')}:GeneratedReferenceCamera",
        "actorId": "",
        "actorName": "GeneratedReferenceCamera",
        "componentName": "GeneratedReferenceCamera",
        "componentClass": "SelfEngineGeneratedReferenceCamera",
        "source": "selfengine_bridge_generated_from_mesh_bounds",
        "transform": {
            "position": position,
            "rotationDegrees": [0.0, 0.0, 0.0],
            "forward": forward,
            "up": up,
            "target": center,
        },
        "fieldOfView": 60.0,
        "aspectRatio": 16.0 / 9.0,
        "nearClipPlane": 1.0,
        "target": center,
        "boundsRadius": radius,
        "generationMessage": "Generated because the UE level contains no CameraComponent; replace with a captured UE viewport bookmark when available.",
    }
    return record


def _reference_capture_record_from_camera(
    scene: Dict[str, Any],
    camera: Dict[str, Any]
) -> Dict[str, Any]:
    scene_id = str(scene.get("id") or scene.get("name") or "scene")
    return {
        "id": f"{scene_id}:GeneratedReferenceCamera",
        "sceneId": scene_id,
        "cameraId": camera.get("id", ""),
        "cameraName": camera.get("actorName", camera.get("componentName", "")),
        "source": "selfengine_bridge_generated_camera_no_screenshot_yet",
        "status": "requires_ue_viewport_screenshot",
        "screenshotPath": "",
        "message": "Camera metadata is ready; capture a matching UE viewport screenshot for visual parity.",
    }


def _upsert_reference_capture(
    scene: Dict[str, Any],
    record: Dict[str, Any]
) -> None:
    record_id = str(record.get("id") or "")
    existing = list(scene.get("referenceCaptures") or [])
    filtered = [
        item for item in existing
        if str(item.get("id") or "") != record_id
    ]
    filtered.append(record)
    scene["referenceCaptures"] = filtered


def _post_process_record(actor: Any) -> Optional[Dict[str, Any]]:
    class_name = _class_name(actor)
    if "PostProcess" not in class_name:
        return None

    settings = _safe_editor_property(actor, "settings", None)
    record: Dict[str, Any] = {
        "id": actor.get_path_name(),
        "actorName": _actor_label(actor),
        "class": class_name,
        "transform": _actor_record(actor)["transform"],
    }
    if settings is not None:
        for field in (
            "auto_exposure_bias",
            "bloom_intensity",
            "film_slope",
            "film_toe",
            "film_shoulder",
            "film_black_clip",
            "film_white_clip",
            "vignette_intensity",
            "motion_blur_amount",
        ):
            value = _safe_editor_property(settings, field, None)
            if isinstance(value, (int, float)) and math.isfinite(float(value)):
                record[field] = float(value)
    return record


def _load_manifest(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8-sig") as file:
        return json.load(file)


def _write_manifest(path: str, manifest: Dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as file:
        json.dump(manifest, file, ensure_ascii=False, indent=2)
        file.write("\n")


def _scene_map_path(scene: Dict[str, Any]) -> str:
    source_asset_id = str(scene.get("sourceAssetId") or scene.get("id") or "")
    if source_asset_id.startswith("/Game/"):
        return source_asset_id

    source_map_path = str(scene.get("sourceMapPath") or "")
    content_path = str(scene.get("contentPath") or "")
    if source_map_path.endswith(".umap"):
        stem = os.path.splitext(os.path.basename(source_map_path))[0]
        return "/Game/" + stem
    return source_asset_id


def _open_map(map_path: str) -> bool:
    if not map_path:
        return False
    try:
        return bool(unreal.EditorLoadingAndSavingUtils.load_map(map_path))
    except Exception as exc:
        _warn(f"Failed to open map {map_path}: {exc}")
        return False


def _all_level_actors() -> Iterable[Any]:
    try:
        return unreal.EditorLevelLibrary.get_all_level_actors()
    except Exception:
        return unreal.EditorActorSubsystem().get_all_level_actors()


def _actor_components(actor: Any) -> Iterable[Any]:
    try:
        return actor.get_components_by_class(unreal.ActorComponent)
    except Exception:
        try:
            return actor.get_components_by_class(unreal.SceneComponent)
        except Exception:
            return []


def _export_scene(scene: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
    map_path = _scene_map_path(scene)
    scene["ueEditorMapPath"] = map_path
    if not _open_map(map_path):
        scene["exportStatus"] = "ue_editor_map_open_failed"
        return scene

    actors: List[Dict[str, Any]] = []
    mesh_instances: List[Dict[str, Any]] = []
    lights: List[Dict[str, Any]] = []
    cameras: List[Dict[str, Any]] = []
    post_process_volumes: List[Dict[str, Any]] = []
    camera_mesh_bounds: Optional[Tuple[List[float], List[float]]] = None
    actor_fallback_locations: List[List[float]] = []

    for actor in _all_level_actors():
        if actor is None:
            continue
        actor_info = _actor_record(actor)
        actors.append(actor_info)
        transform_info = actor_info.get("transform", {})
        if isinstance(transform_info, dict):
            position_info = transform_info.get("position")
            if isinstance(position_info, list) and len(position_info) >= 3:
                actor_fallback_locations.append([
                    float(position_info[0]),
                    float(position_info[1]),
                    float(position_info[2]),
                ])
        post_process = _post_process_record(actor)
        if post_process is not None:
            post_process_volumes.append(post_process)

        for component in _actor_components(actor):
            if component is None:
                continue
            mesh_record = _mesh_component_record(actor, component, context)
            if mesh_record is not None:
                mesh_instances.append(mesh_record)
                bounds = _mesh_component_bounds_for_camera(
                    component,
                    str(mesh_record.get("sourceAssetId") or ""),
                    mesh_record
                )
                if bounds is not None:
                    camera_mesh_bounds = _merge_bounds(camera_mesh_bounds, bounds)
            light_record = _light_component_record(actor, component)
            if light_record is not None:
                lights.append(light_record)
            camera_record = _camera_component_record(actor, component)
            if camera_record is not None:
                cameras.append(camera_record)

    if not cameras:
        fallback_location = [0.0, 0.0, 0.0]
        if actor_fallback_locations:
            total = [0.0, 0.0, 0.0]
            for location in actor_fallback_locations:
                total = _vec_add(total, location)
            fallback_location = _vec_mul(total, 1.0 / float(len(actor_fallback_locations)))
        generated_camera = _generated_reference_camera_record(scene, camera_mesh_bounds, fallback_location)
        cameras.append(generated_camera)
        _upsert_reference_capture(scene, _reference_capture_record_from_camera(scene, generated_camera))
        _log(f"{map_path}: generated fallback reference camera from mesh bounds")

    scene["actors"] = actors
    scene["meshInstances"] = mesh_instances
    scene["lights"] = lights
    scene["cameras"] = cameras
    scene["postProcessVolumes"] = post_process_volumes
    scene["actorCount"] = len(actors)
    scene["meshInstanceCount"] = len(mesh_instances)
    scene["meshExportReadyCount"] = sum(
        1 for mesh in mesh_instances
        if str(mesh.get("exportedPath") or "") and os.path.isfile(str(mesh.get("exportedPath")))
    )
    scene["meshExportMissingCount"] = len(mesh_instances) - scene["meshExportReadyCount"]
    scene["lightCount"] = len(lights)
    scene["cameraCount"] = len(cameras)
    scene["generatedCameraCount"] = sum(
        1 for camera in cameras
        if str(camera.get("source") or "").startswith("selfengine_bridge_generated")
    )
    scene["postProcessVolumeCount"] = len(post_process_volumes)
    scene["referenceCaptureCount"] = len(scene.get("referenceCaptures") or [])
    scene["exportStatus"] = (
        "ue_editor_scene_ready_for_runtime"
        if mesh_instances and scene["meshExportMissingCount"] == 0
        else "ue_editor_metadata_exported"
    )
    scene["metadataExportedAtUtc"] = datetime.now(timezone.utc).isoformat()
    return scene


def _append_diagnostic(manifest: Dict[str, Any], message: str) -> None:
    diagnostics = manifest.setdefault("diagnostics", {})
    entries = diagnostics.setdefault("ueEditorAutomation", [])
    entries.append(
        {
            "timeUtc": datetime.now(timezone.utc).isoformat(),
            "message": message,
        }
    )


def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", default=os.environ.get("SELFENGINE_BRIDGE_MANIFEST", ""))
    parser.add_argument("--scene", default=os.environ.get("SELFENGINE_BRIDGE_SCENE", ""))
    parser.add_argument(
        "--max-scenes",
        type=int,
        default=int(os.environ.get("SELFENGINE_BRIDGE_MAX_SCENES", "0") or "0")
    )
    parser.add_argument("--no-mesh-export", action="store_true")
    parser.add_argument("--force-mesh-export", action="store_true")
    args = parser.parse_args(argv)
    args.no_mesh_export = args.no_mesh_export or (
        os.environ.get("SELFENGINE_BRIDGE_NO_MESH_EXPORT", "").lower() in ("1", "true", "yes", "on")
    )
    args.force_mesh_export = args.force_mesh_export or (
        os.environ.get("SELFENGINE_BRIDGE_FORCE_MESH_EXPORT", "").lower() in ("1", "true", "yes", "on")
    )
    if not args.manifest:
        parser.error("the following arguments are required: --manifest or SELFENGINE_BRIDGE_MANIFEST")
    return args


def main(argv: List[str]) -> int:
    args = parse_args(argv)
    manifest_path = os.path.abspath(args.manifest)
    manifest = _load_manifest(manifest_path)
    export_root = _default_export_root(manifest_path, manifest)
    manifest["exportedRootPath"] = export_root
    mesh_export_root = os.path.join(export_root, "Meshes")
    context: Dict[str, Any] = {
        "export_root": export_root,
        "mesh_export_root": mesh_export_root,
        "export_meshes": not bool(args.no_mesh_export),
        "force_mesh_export": bool(args.force_mesh_export),
        "mesh_export_cache": {},
    }
    scenes = list(manifest.get("scenes") or [])
    if args.scene:
        scenes = [
            scene for scene in scenes
            if args.scene in str(scene.get("id", "")) or args.scene in str(scene.get("name", ""))
        ]
    if args.max_scenes > 0:
        scenes = scenes[: args.max_scenes]

    if not scenes:
        _warn("No scenes selected for UE Editor bridge export")
        _append_diagnostic(manifest, "No scenes selected for UE Editor bridge export")
        _write_manifest(manifest_path, manifest)
        return 2

    _log(f"Exporting metadata for {len(scenes)} scene(s) into {manifest_path}")
    by_id = {str(scene.get("id")): scene for scene in manifest.get("scenes", [])}
    for scene in scenes:
        exported = _export_scene(scene, context)
        scene_id = str(exported.get("id"))
        by_id[scene_id] = exported
        _log(
            f"{scene_id}: actors={exported.get('actorCount', 0)} "
            f"meshes={exported.get('meshInstanceCount', 0)} "
            f"mesh_exports_ready={exported.get('meshExportReadyCount', 0)} "
            f"mesh_exports_missing={exported.get('meshExportMissingCount', 0)} "
            f"lights={exported.get('lightCount', 0)} "
            f"cameras={exported.get('cameraCount', 0)}"
        )

    manifest["scenes"] = list(by_id.values())
    mesh_exports = list(context["mesh_export_cache"].values())
    manifest["meshExports"] = mesh_exports
    manifest["ueEditorMetadataExportedAtUtc"] = datetime.now(timezone.utc).isoformat()
    manifest["ueEditorMeshExportedAtUtc"] = datetime.now(timezone.utc).isoformat()
    diagnostics = manifest.setdefault("diagnostics", {})
    diagnostics["needsUEEditorExportAutomation"] = any(
        scene.get("exportStatus") not in ("ue_editor_metadata_exported", "ue_editor_scene_ready_for_runtime")
        for scene in manifest.get("scenes", [])
    )
    diagnostics["ueEditorMeshExport"] = {
        "enabled": context["export_meshes"],
        "format": "fbx",
        "root": mesh_export_root,
        "uniqueMeshAssetCount": len(mesh_exports),
        "readyCount": sum(1 for item in mesh_exports if item.get("exportedPath")),
        "failedCount": sum(1 for item in mesh_exports if item.get("exportStatus") == "mesh_export_failed"),
        "missingCount": sum(1 for item in mesh_exports if not item.get("exportedPath")),
    }
    _append_diagnostic(
        manifest,
        f"UE Editor metadata export processed {len(scenes)} scene(s); "
        f"unique mesh assets={len(mesh_exports)}"
    )
    _write_manifest(manifest_path, manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
