#pragma once

#include "renderer/vulkan/frame_graph.h"
#include "renderer/vulkan/shadow_settings.h"
#include "renderer/vulkan/uniform_buffer.h"
#include "renderer/vulkan/vulkan_common.h"

#include <array>
#include <string>

namespace se {

struct RendererCpuStats {
    f32 waitAcquireMs = 0.0f;
    f32 imguiMs = 0.0f;
    f32 pickingMs = 0.0f;
    f32 queueBuildMs = 0.0f;
    f32 uniformUpdateMs = 0.0f;
    f32 commandRecordMs = 0.0f;
    f32 submitPresentMs = 0.0f;
    f32 totalFrameMs = 0.0f;
};

struct RendererRenderDebugStats {
    u32 forwardView = 0;
    u32 deferredPbrDebugView = 0;
    u32 usesDeferredHdrComposite = 0;
    u32 temporalReconstructionBypassed = 0;
    u32 lightingEnergyViewEnabled = 0;
};

struct RendererDrawStats {
    u32 mainDraws = 0;
    u32 gBufferDraws = 0;
    u32 overlayDraws = 0;
    u32 shadowDraws = 0;
    u32 hybridDeferredOpaqueDraws = 0;
    u32 hybridForwardTransparentDraws = 0;
    u32 hybridForwardSpecialDraws = 0;
    u32 hybridWeightedTranslucencyDraws = 0;
    u32 hybridWeightedTranslucencySortOps = 0;
    u32 hybridWeightedTranslucencySortedTransparentDraws = 0;
    u32 hybridForwardResidualDraws = 0;
    u32 hybridForwardResidualSortOps = 0;
    u32 hybridForwardResidualSortedTransparentDraws = 0;
    u32 hybridForwardResidualStableSpecialDraws = 0;
    u64 mainTriangles = 0;
    u64 gBufferTriangles = 0;
    u64 overlayTriangles = 0;
    u64 shadowTriangles = 0;
    u64 hybridDeferredOpaqueTriangles = 0;
    u64 hybridWeightedTranslucencyTriangles = 0;
    u64 hybridForwardResidualTriangles = 0;
    u32 matrixRecalculations = 0;
    u32 mainVisible = 0;
    u32 mainCulled = 0;
    u32 overlayVisible = 0;
    u32 overlayCulled = 0;
    u32 shadowVisible = 0;
    u32 shadowCulled = 0;
    u32 mainBoundsCacheHits = 0;
    u32 mainBoundsCacheMisses = 0;
    u32 mainCommandCacheHits = 0;
    u32 mainCommandCacheMisses = 0;
    u32 mainVisibilityCacheHits = 0;
    u32 mainVisibilityCacheMisses = 0;
    u32 mainQueueCacheHits = 0;
    u32 mainQueueCacheMisses = 0;
    u32 overlayBoundsCacheHits = 0;
    u32 overlayBoundsCacheMisses = 0;
    u32 overlayCommandCacheHits = 0;
    u32 overlayCommandCacheMisses = 0;
    u32 overlayVisibilityCacheHits = 0;
    u32 overlayVisibilityCacheMisses = 0;
    u32 overlayQueueCacheHits = 0;
    u32 overlayQueueCacheMisses = 0;
    u32 mainInstancedDraws = 0;
    u32 mainInstancedInstances = 0;
    u32 mainInstanceBatchCacheHits = 0;
    u32 mainInstanceBatchCacheMisses = 0;
    u32 mainSkinnedConservativeBounds = 0;
    u32 shadowSkinnedConservativeBounds = 0;
};

struct RendererShadowCascadeStats {
    u32 budgetContractVersion = 0;
    u32 budgetResourceContractValid = 0;
    u32 budgetFallbackReason = 0;
    u32 budgetSwapchainImageCount = 0;
    u32 budgetGenerationMaxPasses = 0;
    u32 budgetDirectionalReceiverSamples = 0;
    u32 budgetPointProjectionSamples = 0;
    u32 budgetSpotProjectionSamples = 0;
    u32 budgetRectProjectionSamples = 0;
    u32 budgetRectProjectionCount = 0;
    u32 budgetContactSamples = 0;
    u32 budgetGpuGenerationScope = 0;
    u64 budgetLegacyDepthBytes = 0;
    u64 budgetDirectionalDepthBytes = 0;
    u64 budgetLocalDepthBytes = 0;
    u64 budgetMainDepthBytes = 0;
    u32 quality = 0;
    u32 configuredCount = 0;
    u32 activeCount = 0;
    u32 directionalReceiveEnabled = 0;
    u32 stableSnappingEnabled = 0;
    u32 atlasAllocated = 0;
    u32 atlasTileSize = 0;
    u32 atlasWidth = 0;
    u32 atlasHeight = 0;
    u32 atlasTileColumns = 0;
    u32 atlasTileRows = 0;
    u32 atlasCascadeCapacity = 0;
    u32 pcfKernelRadius = 0;
    u32 filterMode = 0;
    u32 filterSampleCount = 0;
    u32 filterKernelWidth = 0;
    u32 filterMaxDepthSamples = 0;
    u32 filterHardwareCompareEnabled = 0;
    u32 filterFallbackReason = 0;
    u32 receiverPlaneBiasEnabled = 0;
    u32 normalOffsetBiasEnabled = 0;
    u32 slopeOffsetBiasEnabled = 0;
    u32 casterDepthBiasEnabled = 0;
    u32 pcssEnabled = 0;
    u32 pcssBlockerSampleCount = 0;
    u32 pcssFilterSampleCount = 0;
    u32 pcssRawDepthSamplerReady = 0;
    u32 pcssFallbackReason = 0;
    u32 pcssGrazingFadeEnabled = 0;
    f32 pcssStrength = 0.0f;
    f32 pcssSearchRadiusTexels = 0.0f;
    f32 pcssMaxPenumbraTexels = 0.0f;
    f32 pcssLightAngularRadiusRadians = 0.0f;
    f32 pcssGrazingFadeStart = 0.0f;
    f32 pcssGrazingFadeEnd = 0.0f;
    f32 filterReceiverBiasExtentTexels = 0.0f;
    f32 receiverPlaneBiasScale = 0.0f;
    f32 normalOffsetBiasTexels = 0.0f;
    f32 slopeOffsetBiasTexels = 0.0f;
    f32 casterDepthBiasConstant = 0.0f;
    f32 casterDepthBiasClamp = 0.0f;
    f32 casterDepthBiasSlope = 0.0f;
    f32 splitLambda = 0.0f;
    f32 maxDistance = 0.0f;
    f32 blendRatio = 0.0f;
    f32 fadeRatio = 0.0f;
    f32 receiverGuardRatio = 0.0f;
    f32 contactShadowStrength = 0.0f;
    f32 contactShadowLength = 0.0f;
    f32 contactShadowThickness = 0.0f;
    u32 contactShadowSteps = 0;
    f32 contactShadowJitterStrength = 0.0f;
    f32 contactShadowEdgeFadePixels = 0.0f;
    f32 nearDepth = 0.0f;
    f32 farDepth = 0.0f;
    std::array<f32, kMaxDirectionalShadowCascades> splitDepths{};
    std::array<f32, kMaxDirectionalShadowCascades> texelWorldSizes{};
    std::array<f32, kMaxDirectionalShadowCascades> lightDepthWorldSpans{};
};

struct RendererLocalShadowAtlasStats {
    u32 allocated = 0;
    u32 tileSize = 0;
    u32 atlasWidth = 0;
    u32 atlasHeight = 0;
    u32 tileColumns = 0;
    u32 tileRows = 0;
    u32 tileCapacity = 0;
    u32 shadowableLocalLights = 0;
    u32 pointLightCount = 0;
    u32 spotLightCount = 0;
    u32 rectLightCount = 0;
    u32 pointFaceTiles = 0;
    u32 spotTiles = 0;
    u32 rectTiles = 0;
    u32 requestedTiles = 0;
    u32 assignedTiles = 0;
    u32 droppedTiles = 0;
    u32 recordedTilePasses = 0;
    u32 recordedDraws = 0;
    u32 recordedMeshBinds = 0;
    u32 cacheEligibleTiles = 0;
    u32 cacheHitTiles = 0;
    u32 cacheMissTiles = 0;
    u32 cacheSkippedTiles = 0;
    u32 cacheColdTiles = 0;
    u32 cacheTileLayoutChangedTiles = 0;
    u32 cacheLightChangedTiles = 0;
    u32 cacheCasterChangedTiles = 0;
    u32 cacheDynamicSkinnedCasterTiles = 0;
    std::string cacheReasonSummary;
    u32 pcfKernelRadius = 0;
    f32 biasMin = 0.0f;
    f32 biasSlope = 0.0f;
    f32 pcfRadius = 0.0f;
    f32 pcssStrength = 0.0f;
    u32 filterContractVersion = 0;
    u32 productionFilterEnabled = 0;
    u32 productionFilterReady = 0;
    u32 productionFilterActive = 0;
    u32 productionFilterFallbackReason = 0;
    u32 comparisonSamplerReady = 0;
    u32 rawDepthSamplerReady = 0;
    u32 tileRangeContractValid = 0;
    u32 tileRangeInvalidLights = 0;
    u32 tileRangeMaxTilesPerLight = 0;
    u32 filterGeometryValidTiles = 0;
    u32 filterGeometryInvalidTiles = 0;
    u32 pointPcssBlockerSamples = 0;
    u32 pointPcssFilterSamples = 0;
    f32 pointPcssSearchRadiusTexels = 0.0f;
    f32 pointPcssMaxPenumbraTexels = 0.0f;
    u32 spotPcssBlockerSamples = 0;
    u32 spotPcssFilterSamples = 0;
    f32 spotPcssSearchRadiusTexels = 0.0f;
    f32 spotPcssMaxPenumbraTexels = 0.0f;
    u32 rectPcssBlockerSamples = 0;
    u32 rectPcssFilterSamples = 0;
    f32 rectPcssSearchRadiusTexels = 0.0f;
    f32 rectPcssMaxPenumbraTexels = 0.0f;
    f32 faceBlendStrength = 0.0f;
    f32 rectBiasScale = 8.0f;
    f32 pointBiasMin = 0.0f;
    f32 pointBiasSlope = 0.0f;
    f32 pointPcfRadius = 0.0f;
    u32 pointPcfKernelRadius = 0;
    f32 pointPcssStrength = 0.0f;
    f32 spotBiasMin = 0.0f;
    f32 spotBiasSlope = 0.0f;
    f32 spotPcfRadius = 0.0f;
    u32 spotPcfKernelRadius = 0;
    f32 spotPcssStrength = 0.0f;
    f32 rectBiasMin = 0.0f;
    f32 rectBiasSlope = 0.0f;
    f32 rectPcfRadius = 0.0f;
    u32 rectPcfKernelRadius = 0;
    f32 rectPcssStrength = 0.0f;
    u32 rectShadowBaseSampleTiles = 0;
    u32 rectShadowMaxSampleTiles = 0;
    u32 rectShadowSamplePattern = 0;
    u32 rectShadowExtraSampleTiles = 0;
    u32 rectShadowBudgetLimitedSampleTiles = 0;
    u32 pointShadowEnabled = 1;
    u32 spotShadowEnabled = 1;
    u32 rectShadowEnabled = 1;
    i32 debugLightIndex = -1;
    i32 attributionLightIndex = -1;
    u32 attributionLightValid = 0;
    u32 attributionLightKind = 0;
    u32 attributionExpectedTiles = 0;
    u32 attributionRequestedTiles = 0;
    u32 attributionAssignedTiles = 0;
    u32 attributionDroppedTiles = 0;
    u32 attributionCacheHitTiles = 0;
    u32 attributionCacheMissTiles = 0;
    u32 attributionRecordedTilePasses = 0;
    u32 attributionRecordedDraws = 0;
    u32 attributionCandidateDraws = 0;
    u32 attributionUniqueCasters = 0;
    u64 attributionCasterSignature = 0;
    std::string attributionTileCandidateDraws;
    std::string attributionCasterSummary;
    u32 attributionShadowEnabled = 0;
    u32 attributionMatchesGenerationFilter = 0;
};

struct RendererWeightedTranslucencyStats {
    u32 allocated = 0;
    u32 accumWidth = 0;
    u32 accumHeight = 0;
    u32 revealageWidth = 0;
    u32 revealageHeight = 0;
    VkFormat accumFormat = VK_FORMAT_UNDEFINED;
    VkFormat revealageFormat = VK_FORMAT_UNDEFINED;
    u32 renderPassAllocated = 0;
    u32 framebufferCount = 0;
    u32 clearPasses = 0;
    u32 draws = 0;
    u32 sharedLightListDraws = 0;
    u32 shadowReadyDraws = 0;
    u32 resolveDraws = 0;
};

struct RendererSsaoStats {
    u32 enabled = 0;
    f32 strength = 0.0f;
    f32 radius = 0.0f;
    f32 bias = 0.0f;
    u32 sampleCount = 0;
};

struct RendererSsrStats {
    u32 enabled = 0;
    u32 colorResolveEnabled = 0;
    u32 traceInputsReady = 0;
    u32 hierarchicalRequested = 0;
    u32 hierarchicalActive = 0;
    u32 hierarchicalFallbackReason = 0;
    u32 fixedStepFallbackActive = 0;
    u32 depthPyramidAllocated = 0;
    u32 depthPyramidReady = 0;
    u32 depthPyramidWidth = 0;
    u32 depthPyramidHeight = 0;
    u32 depthPyramidMipCount = 0;
    u32 depthPyramidImageCount = 0;
    VkFormat depthPyramidFormat = VK_FORMAT_UNDEFINED;
    u64 depthPyramidMemoryBytes = 0;
    u32 depthPyramidBuildDispatchCount = 0;
    u64 depthPyramidGeneratedMipMask = 0;
    u32 traversalMaxMip = 0;
    u32 refinementEnabled = 0;
    u32 refinementStepCount = 0;
    u32 hitValidationRequested = 0;
    u32 hitValidationActive = 0;
    u32 hitValidationContractVersion = 0;
    u32 hitNormalValidationEnabled = 0;
    u32 hitFootprintTapCount = 0;
    u32 signedDepthValidationEnabled = 0;
    f32 originBiasMinimumPixels = 0.0f;
    f32 originBiasMaximumPixels = 0.0f;
    u32 reconstructionRequested = 0;
    u32 reconstructionActive = 0;
    u32 reconstructionTargetsAllocated = 0;
    u32 reconstructionDescriptorSetsReady = 0;
    u32 reconstructionTraceDispatches = 0;
    u32 reconstructionTemporalDispatches = 0;
    u32 reconstructionSpatialDispatches = 0;
    u32 reconstructionHistoryCopies = 0;
    u32 reconstructionHistoryReset = 0;
    u32 reconstructionImageCount = 0;
    u64 reconstructionMemoryBytes = 0;
    u32 reconstructionTemporalContractVersion = 0;
    u32 reconstructionTemporalMissHistoryRejectEnabled = 0;
    u32 reconstructionTemporalPreviousViewDepthEnabled = 0;
    u32 reconstructionTemporalHistoryLockEnabled = 0;
    u32 reconstructionSpatialCenterHitGateEnabled = 0;
    u32 reconstructionSpatialVarianceClampEnabled = 0;
    u32 reconstructionSpatialSupportTapCount = 0;
    u32 reconstructionRawResolvedAliased = 0;
    u32 reconstructionCurrentHdrSourceEnabled = 0;
    u32 reconstructionCurrentHdrRadianceFilterEnabled = 0;
    u32 reconstructionCurrentHdrMipLevels = 0;
    u32 reconstructionCurrentHdrMipChainReady = 0;
    u32 fallbackBlendRequested = 0;
    u32 fallbackBlendActive = 0;
    u32 fallbackBlendContractVersion = 0;
    u32 fallbackBlendResolvedPixels = 0;
    u32 fallbackBlendPartialPixels = 0;
    u32 fallbackBlendHighTrustPixels = 0;
    u32 fallbackBlendAveragePermille = 0;
    u32 reconstructionDeferredConsumerContractVersion = 0;
    u32 reconstructionDeferredReceiverReprojectionEnabled = 0;
    u32 reconstructionDeferredDepthRejectEnabled = 0;
    u32 reconstructionDeferredNormalRejectEnabled = 0;
    u32 reconstructionDeferredRoughnessRejectEnabled = 0;
    u32 reconstructionDeferredMetadataDescriptorBound = 0;
    u32 reconstructionResolvedMetadataAliased = 0;
    u32 reflectionProbeFallbackEnabled = 0;
    u32 sceneColorHistoryRequested = 0;
    u32 sceneColorHistoryDescriptorBound = 0;
    u32 sceneColorHistoryReady = 0;
    u32 sceneColorHistoryActive = 0;
    u32 sceneColorHistoryFallbackReason = 0;
    u32 sceneColorHistorySourceValid = 0;
    u32 sceneColorHistoryCurrentImageIndex = 0;
    u32 sceneColorHistorySourceImageIndex = 0;
    u32 sceneColorHistoryFrameAge = 0;
    // 0 = off, 1 = probe/IBL fallback, 2 = completed scene-color history.
    u32 radianceSource = 0;
    f32 strength = 0.0f;
    f32 rayLength = 0.0f;
    f32 thickness = 0.0f;
    u32 stepCount = 0;
    // Debug-only GPU evidence for distinguishing sparse SSR hits from
    // temporal/spatial rejection. These stay zero when the audit is disabled.
    u32 holeDiagnosticsRequested = 0;
    u32 holeDiagnosticsActive = 0;
    u32 holeDiagnosticsReadbackValid = 0;
    u32 holeDiagnosticsPixelCount = 0;
    u32 holeDiagnosticsRawHitPixels = 0;
    u32 holeDiagnosticsRawHighConfidencePixels = 0;
    u32 holeDiagnosticsTemporalValidPixels = 0;
    u32 holeDiagnosticsResolvedValidPixels = 0;
    u32 holeDiagnosticsIsolatedRawHitPixels = 0;
    u32 holeDiagnosticsCenterMissNeighborHitPixels = 0;
    u32 holeDiagnosticsResolvedHolePixels = 0;
    u32 holeDiagnosticsRawHitTemporalRejectedPixels = 0;
    u32 holeDiagnosticsRawHitSpatialRejectedPixels = 0;
    u32 holeDiagnosticsTemporalMissCarriedPixels = 0;
    u32 holeDiagnosticsContractVersion = 0;
};

struct RendererIblStats {
    u32 quality = 1;
    u32 requestedSource = 0;
    u32 actualSource = 0;
    u32 sourceFallbackReason = 0;
    u32 cachePolicy = 0;
    u32 cacheFallbackReason = 0;
    u32 cacheHit = 0;
    u32 runtimeGenerated = 1;
    u32 sourceAssetSpecified = 0;
    u32 sourceAssetFound = 0;
    u64 sourceSignature = 0;
    u32 brdfLutAllocated = 0;
    u32 brdfLutSize = 0;
    VkFormat brdfLutFormat = VK_FORMAT_UNDEFINED;
    u32 irradianceMapAllocated = 0;
    u32 irradianceFaceSize = 0;
    VkFormat irradianceFormat = VK_FORMAT_UNDEFINED;
    u32 prefilteredMapAllocated = 0;
    u32 prefilteredFaceSize = 0;
    u32 prefilteredMipCount = 0;
    VkFormat prefilteredFormat = VK_FORMAT_UNDEFINED;
    u32 descriptorSetsBound = 0;
    u32 shaderIntegrationEnabled = 0;
};

enum class RendererProbeGridFallbackReason : u32 {
    None = 0,
    Disabled = 1,
    BlendZero = 2,
    BufferUnavailable = 3,
    InvalidLayout = 4,
    FrameIndexOutOfRange = 5
};

struct RendererProbeGridStats {
    u32 allocated = 0;
    u32 enabled = 0;
    u32 shaderIntegrationEnabled = 0;
    u32 bufferUpdates = 0;
    u32 fallbackCount = 0;
    u32 fallbackReason = 0;
    u32 probeCount = 0;
    u32 sizeX = 0;
    u32 sizeY = 0;
    u32 sizeZ = 0;
    u32 vec4sPerProbe = 0;
    u32 directionalLobeCount = 0;
    u32 cellCount = 0;
    f32 originX = 0.0f;
    f32 originY = 0.0f;
    f32 originZ = 0.0f;
    f32 boundsMinX = 0.0f;
    f32 boundsMinY = 0.0f;
    f32 boundsMinZ = 0.0f;
    f32 boundsMaxX = 0.0f;
    f32 boundsMaxY = 0.0f;
    f32 boundsMaxZ = 0.0f;
    f32 spacing = 0.0f;
    f32 blendStrength = 0.0f;
    u32 debugViewEnabled = 0;
    u32 cellDebugViewEnabled = 0;
};

struct RendererBonePaletteDrawStats {
    u32 commandCount = 0;
    u32 readyCommandCount = 0;
    u32 resourceCount = 0;
    u32 readyResourceCount = 0;
    u32 currentEntryCount = 0;
    u32 previousEntryCount = 0;
    u32 changedEntryCount = 0;
    u32 drawPathReady = 0;
    u32 descriptorCommandCount = 0;
    u32 descriptorReadyCommandCount = 0;
    u32 descriptorResourceCount = 0;
    u32 descriptorReadyResourceCount = 0;
    u32 descriptorSetIndex = 0;
    u32 descriptorBinding = 0;
    u32 descriptorRangeBytes = 0;
    u32 descriptorPathReady = 0;
    u32 shaderConsumerCommandCount = 0;
    u32 shaderConsumerReadyCommandCount = 0;
    u32 shaderConsumerFallbackDescriptorReady = 0;
    u32 shaderConsumerPathReady = 0;
    u32 shaderSkinningCommandCount = 0;
    u32 shaderSkinningReadyCommandCount = 0;
    u32 shaderSkinningCurrentPaletteOffset = 0;
    u32 shaderSkinningCurrentEntryCount = 0;
    u32 shaderSkinningPathReady = 0;
    u32 shaderVelocityCommandCount = 0;
    u32 shaderVelocityReadyCommandCount = 0;
    u32 shaderVelocityPreviousPaletteOffset = 0;
    u32 shaderVelocityPreviousEntryCount = 0;
    u32 shaderVelocityPathReady = 0;
};

struct RendererReflectionProbeStats {
    u32 fallbackEnabled = 0;
    f32 diffuseIntensity = 0.0f;
    f32 specularIntensity = 0.0f;
    f32 horizonBlend = 0.0f;
    u32 globalIblCubemapSamplingEnabled = 0;
    u32 sceneProbeCount = 0;
    u32 activeProbeCount = 0;
    u32 sceneEligibleProbeCount = 0;
    u32 selectedProbeCount = 0;
    u32 blendedProbeCount = 0;
    u32 selectedCaptureSlotCount = 0;
    u32 selectedCaptureResourceReadyCount = 0;
    u32 selectedCaptureFallbackCount = 0;
    u32 selectedCubemapSamplingCount = 0;
    u32 selectedCaptureReadyMask = 0;
    u32 selectedCaptureFallbackMask = 0;
    u32 selectedCubemapSamplingMask = 0;
    u32 selectedAuthoredAssetSpecifiedCount = 0;
    u32 selectedAuthoredAssetFoundCount = 0;
    u32 selectedAuthoredAssetMissingCount = 0;
    u32 selectedAuthoredAssetSpecifiedMask = 0;
    u32 selectedAuthoredAssetFoundMask = 0;
    u32 selectedAuthoredAssetMissingMask = 0;
    u32 capturedSceneRequestedCount = 0;
    u32 capturedScenePlaceholderAllocatedCount = 0;
    u32 capturedScenePlaceholderReadyCount = 0;
    u32 capturedSceneInvalidatedCount = 0;
    u32 capturedSceneRefreshRequestedCount = 0;
    u32 capturedSceneCaptureBackend = 0;
    u32 capturedSceneFaceCount = 0;
    u32 capturedSceneFacesRendered = 0;
    u32 capturedSceneFacesPending = 0;
    u32 capturedSceneCapturePassCount = 0;
    u32 capturedSceneCaptureDrawCount = 0;
    u32 capturedSceneCaptureVisibleCount = 0;
    u32 capturedSceneCaptureCulledCount = 0;
    u32 capturedSceneCaptureFaceOrientationMask = 0;
    u32 capturedSceneMipGenerationCount = 0;
    u32 capturedSceneSourceMipGenerationCount = 0;
    u32 capturedSceneSourceMipCount = 0;
    u64 capturedSceneSourceMipMemoryBytes = 0;
    u32 capturedSceneSourceMipChainReady = 0;
    u32 capturedSceneGgxPrefilterSourceImageSeparated = 0;
    u32 capturedSceneGgxPrefilterPdfLodEnabled = 0;
    u32 capturedSceneGgxPrefilterDispatchCount = 0;
    u32 capturedSceneGgxPrefilterSampleCount = 0;
    u32 capturedSceneGgxPrefilterQuality = 0;
    u32 capturedSceneDiffuseIrradianceDispatchCount = 0;
    u32 capturedSceneDiffuseIrradianceSampleCount = 0;
    u32 capturedSceneDiffuseIrradianceFaceSize = 0;
    u32 capturedSceneDirectionalShadowRequested = 0;
    u32 capturedSceneDirectionalShadowReady = 0;
    u32 capturedSceneDirectionalShadowPassCount = 0;
    u32 capturedSceneDirectionalShadowDrawCount = 0;
    u32 capturedSceneDirectionalShadowCasterCount = 0;
    u32 capturedSceneDirectionalShadowMapSize = 0;
    u32 capturedSceneDirectionalShadowFaceMask = 0;
    u32 capturedSceneDirectionalShadowCameraIndependent = 0;
    u32 capturedSceneDirectionalShadowLocalTilesSuppressed = 0;
    i32 capturedSceneDirectionalShadowProbeSceneIndex = -1;
    u32 capturedSceneLocalShadowRequested = 0;
    u32 capturedSceneLocalShadowReady = 0;
    u32 capturedSceneLocalShadowPassCount = 0;
    u32 capturedSceneLocalShadowDrawCount = 0;
    u32 capturedSceneLocalShadowCasterCount = 0;
    u32 capturedSceneLocalShadowTileCount = 0;
    u32 capturedSceneLocalShadowPointFaceTileCount = 0;
    u32 capturedSceneLocalShadowSpotTileCount = 0;
    u32 capturedSceneLocalShadowRectTileCount = 0;
    u32 capturedSceneLocalShadowRequestedTileCount = 0;
    u32 capturedSceneLocalShadowDroppedTileCount = 0;
    u32 capturedSceneLocalShadowRectRequestedTileCount = 0;
    u32 capturedSceneLocalShadowRectMaximumTileCount = 0;
    u32 capturedSceneLocalShadowRectExtraSampleTileCount = 0;
    u32 capturedSceneLocalShadowRectBudgetLimitedSampleTileCount = 0;
    u32 capturedSceneLocalShadowRectDroppedTileCount = 0;
    u32 capturedSceneLocalShadowMapTileSize = 0;
    u32 capturedSceneLocalShadowFaceMask = 0;
    u32 capturedSceneLocalShadowSupportedKindMask = 0;
    u32 capturedSceneLocalShadowSuppressedKindMask = 0;
    u32 capturedSceneLocalShadowCameraIndependent = 0;
    i32 capturedSceneLocalShadowProbeSceneIndex = -1;
    u32 capturedSceneShadowSnapshotBuildCount = 0;
    u32 capturedSceneShadowSnapshotReuseFaceCount = 0;
    u32 capturedSceneShadowSnapshotSavedDirectionalPassCount = 0;
    u32 capturedSceneShadowSnapshotSavedLocalTilePassCount = 0;
    u32 capturedSceneShadowSnapshotSavedLocalDrawCount = 0;
    u32 capturedSceneShadowSnapshotBuildFaceMask = 0;
    u32 capturedSceneShadowSnapshotReuseFaceMask = 0;
    i32 capturedSceneShadowSnapshotProbeSceneIndex = -1;
    i32 capturedSceneShadowSnapshotPersistentCacheSlot = -1;
    u32 capturedSceneShadowSnapshotPersistentHitCount = 0;
    u32 capturedSceneShadowSnapshotPersistentCacheResourceCount = 0;
    u32 capturedSceneShadowSnapshotPersistentCacheEvictionCount = 0;
    u32 capturedSceneShadowSnapshotInputSignature = 0;
    u32 capturedSceneShadowSnapshotReady = 0;
    u32 capturedSceneShadowSnapshotCameraIndependent = 0;
    u32 capturedSceneShadowSnapshotEnabled = 0;
    u32 capturedSceneShadowSnapshotFallbackActive = 0;
    u32 capturedSceneShadowSnapshotPersistentEnabled = 0;
    u32 capturedSceneShadowSnapshotPersistentHit = 0;
    u32 capturedScenePersistentShadowCacheCapacity = 0;
    u32 capturedScenePersistentShadowCacheResourceCount = 0;
    u32 capturedScenePersistentShadowCacheEvictionCount = 0;
    std::array<i32, 2> capturedScenePersistentShadowCacheProbeSceneIndices = {
        -1,
        -1
    };
    std::array<u32, 2> capturedScenePersistentShadowCacheInputSignatures{};
    u32 capturedSceneLastCapturedFace = 0;
    u32 capturedSceneRasterizedGeometry = 0;
    u32 capturedSceneGpuResourcesAllocated = 0;
    u32 capturedSceneGpuCaptureInProgress = 0;
    u32 capturedSceneCaptureFaceOrientationValid = 0;
    u32 capturedSceneMipChainReady = 0;
    u32 capturedSceneGgxPrefilterReady = 0;
    u32 capturedSceneGgxPrefilterFallbackActive = 0;
    u32 capturedSceneDiffuseIrradianceReady = 0;
    i32 capturedSceneProbeSceneIndex = -1;
    u32 selectedCapturedSceneMapMatchesActiveMask = 0;
    u32 selectedCapturedSceneDuplicateActiveViewMask = 0;
    u32 selectedCapturedSceneDiffuseIrradianceMapMatchesActiveMask = 0;
    u32 selectedCapturedSceneDiffuseIrradianceDuplicateActiveViewMask = 0;
    u32 capturedSceneProbeResourceCount = 0;
    u32 capturedSceneReadyProbeCount = 0;
    u32 capturedSceneInFlightProbeCount = 0;
    u32 capturedSceneDistinctActiveViewCount = 0;
    u32 capturedSceneDiffuseIrradianceReadyProbeCount = 0;
    u32 capturedSceneDistinctActiveDiffuseIrradianceViewCount = 0;
    u32 capturedSceneUploadCount = 0;
    u32 capturedSceneRefreshCheckCount = 0;
    u32 capturedSceneRefreshPerformed = 0;
    u32 capturedSceneRefreshReason = 0;
    u32 capturedSceneLastRefreshReason = 0;
    u32 capturedSceneDirtyMask = 0;
    u32 capturedSceneActiveSignature = 0;
    u32 capturedSceneRequestedSignature = 0;
    u32 capturedSceneRadianceSignature = 0;
    u64 capturedSceneMembershipRevision = 0;
    u64 capturedSceneLightRevision = 0;
    u64 capturedSceneRenderRevision = 0;
    u64 capturedSceneSchedulerFrame = 0;
    u64 capturedSceneLastRefreshCompletedFrame = 0;
    u32 capturedSceneLocalLightSignature = 0;
    u32 capturedSceneGeometrySignature = 0;
    u32 capturedSceneAffectedLocalLightCount = 0;
    u32 capturedSceneAffectedRenderableCount = 0;
    u32 capturedSceneRefreshPriority = 0;
    u32 capturedSceneMinimumRefreshIntervalFrames = 0;
    u32 capturedSceneRefreshDeferredCount = 0;
    u32 capturedSceneSelectiveInvalidationEnabled = 0;
    u32 capturedSceneRefreshDeferredByBudget = 0;
    u32 capturedSceneLocalityIgnoredLightRevisionCount = 0;
    u32 capturedSceneLocalityIgnoredGeometryRevisionCount = 0;
    u32 forcedRefreshRequested = 0;
    u32 sceneDirtyRequested = 0;
    u32 authoredCubemapLoadedCount = 0;
    u32 authoredCubemapMissingCount = 0;
    u32 authoredCubemapLoadFailedCount = 0;
    u32 authoredCubemapUploadCount = 0;
    u32 authoredCubemapSixFaceLoadedCount = 0;
    u32 authoredCubemapEquirectangularLoadedCount = 0;
    u32 authoredCubemapEquirectangularConversionCount = 0;
    u32 authoredCubemapHdrLoadedCount = 0;
    u32 authoredCubemapPrefilteredLoadedCount = 0;
    u32 authoredCubemapPrefilteredUploadCount = 0;
    u32 authoredCubemapCacheHitCount = 0;
    u32 authoredCubemapReloadCount = 0;
    u32 authoredCubemapRefreshCheckCount = 0;
    u32 authoredCubemapFaceSize = 0;
    u32 authoredCubemapMipCount = 0;
    VkFormat authoredCubemapFormat = VK_FORMAT_UNDEFINED;
    u32 authoredCubemapSourceType = 0;
    u32 authoredCubemapHdr = 0;
    u32 authoredCubemapPrefiltered = 0;
    u32 authoredCubemapGeneratedMipCount = 0;
    u32 authoredCubemapPrefilterSampleCount = 0;
    u32 authoredCubemapPrefilterMode = 0;
    u32 authoredCubemapFilterQuality = 1;
    u32 authoredCubemapSeamAwareFiltering = 0;
    u32 authoredCubemapIrradianceReadyCount = 0;
    u32 authoredCubemapIrradianceApplied = 0;
    f32 authoredCubemapIrradianceR = 0.0f;
    f32 authoredCubemapIrradianceG = 0.0f;
    f32 authoredCubemapIrradianceB = 0.0f;
    u32 authoredCubemapDiffuseLobesReadyCount = 0;
    u32 authoredCubemapDiffuseLobesApplied = 0;
    u32 authoredCubemapDiffuseLobeCount = 0;
    u32 selectedDiffuseLobeReadyMask = 0;
    u32 selectedCapturedSceneDiffuseIrradianceReadyMask = 0;
    f32 authoredCubemapDiffuseLobeEnergy = 0.0f;
    u32 droppedProbeCount = 0;
    i32 selectedProbeIndex = -1;
    u32 selectedProbeMask = 0;
    u32 selectedBoxProjectionMask = 0;
    u32 selectedCapturedSceneBoxProjectionMask = 0;
    u32 selectedBoxProjectionRayHitMask = 0;
    u32 selectedBoxProjectionDirectionChangedMask = 0;
    u32 selectedBoxProjectionOutsideFallbackMask = 0;
    u32 selectedSceneOwnedMask = 0;
    u32 selectedPositiveInfluenceMask = 0;
    u32 blendWeightNormalizationFallbackCount = 0;
    std::array<i32, kMaxFrameReflectionProbes> selectedProbeIndices{};
    std::array<i32, kMaxFrameReflectionProbes> selectedCaptureSlots{};
    std::array<u32, kMaxFrameReflectionProbes> selectedCaptureSourceTypes{};
    std::array<u32, kMaxFrameReflectionProbes> selectedCaptureFallbackReasons{};
    std::array<u32, kMaxFrameReflectionProbes> selectedRefreshPolicies{};
    std::array<u32, kMaxFrameReflectionProbes> selectedCapturedScenePlaceholderReady{};
    std::array<u32, kMaxFrameReflectionProbes> selectedCapturedSceneInvalidated{};
    std::array<u32, kMaxFrameReflectionProbes> selectedCaptureMipCounts{};
    std::array<u32, kMaxFrameReflectionProbes> selectedAuthoredAssetHashes{};
    f32 maxBlendWeight = 0.0f;
    f32 totalBlendWeight = 0.0f;
    f32 normalizedBlendWeightSum = 0.0f;
    f32 normalizedBlendWeightError = 0.0f;
    std::array<f32, kMaxFrameReflectionProbes> selectedBlendWeights{};
    std::array<f32, kMaxFrameReflectionProbes> selectedNormalizedBlendWeights{};
    u32 receiverAuditRequested = 0;
    u32 receiverAuditProductionBlend = 0;
    u32 receiverAuditIndependentIblEnergy = 0;
    f32 receiverAuditPositionX = 0.0f;
    f32 receiverAuditPositionY = 0.0f;
    f32 receiverAuditPositionZ = 0.0f;
    f32 receiverAuditDirectionX = 0.0f;
    f32 receiverAuditDirectionY = 0.0f;
    f32 receiverAuditDirectionZ = 1.0f;
    f32 receiverAuditRoughness = 0.0f;
    u32 receiverAuditPositiveWeightMask = 0;
    u32 receiverAuditReadyCubemapMask = 0;
    u32 receiverAuditBoxProjectionHitMask = 0;
    i32 receiverAuditDominantSlot = -1;
    f32 receiverAuditTotalWeight = 0.0f;
    f32 receiverAuditLocalCoverage = 0.0f;
    f32 receiverAuditDominantNormalizedWeight = 0.0f;
    f32 receiverAuditLocalCubemapWeight = 0.0f;
    std::array<f32, kMaxFrameReflectionProbes> receiverAuditWeights{};
    std::array<f32, kMaxFrameReflectionProbes> receiverAuditNormalizedWeights{};
    std::array<f32, kMaxFrameReflectionProbes> receiverAuditResolvedLods{};
    u32 capturedSceneNeutralTintMask = 0;
    u32 selectedProbeDuplicateIndexMask = 0;
    u32 selectedCaptureMipReadyMask = 0;
    u32 spatialContractFailureMask = 0;
    u32 spatialContractValid = 0;
    u32 multiBlendEnabled = 0;
    u32 localEnabled = 0;
    u32 localSceneOwned = 0;
    f32 localRadius = 0.0f;
    f32 localBoxExtentX = 0.0f;
    f32 localBoxExtentY = 0.0f;
    f32 localBoxExtentZ = 0.0f;
    f32 localIntensity = 0.0f;
    f32 localBlendStrength = 0.0f;
    f32 localFalloff = 0.0f;
    u32 localCubemapAllocated = 0;
    u32 localCubemapFaceSize = 0;
    u32 localCubemapMipCount = 0;
    VkFormat localCubemapFormat = VK_FORMAT_UNDEFINED;
    u32 localCubemapDescriptorSetsBound = 0;
    u32 localCubemapShaderSamplingEnabled = 0;
    u32 localCubemapSourceType = 0;
    u32 captureSourceType = 0;
    u32 refreshPolicy = 0;
    u32 captureResourceReady = 0;
    u32 captureFallbackReason = 0;
    u32 captureDescriptorBound = 0;
    u32 boxProjectionEnabled = 0;
    u32 influenceMode = 0;
    u32 parallaxCorrectionEnabled = 0;
};

struct RendererHeightFogStats {
    u32 enabled = 0;
    f32 density = 0.0f;
    f32 heightFalloff = 0.0f;
    f32 startDistance = 0.0f;
    f32 maxOpacity = 0.0f;
};

struct RendererPostProcessStats {
    u32 bloomEnabled = 0;
    f32 bloomIntensity = 0.0f;
    f32 bloomThreshold = 0.0f;
    f32 bloomRadiusPixels = 0.0f;
    u32 bloomPyramidEnabled = 0;
    u32 bloomPyramidMipCount = 0;
    u32 bloomPyramidFallbacks = 0;
    u32 toneMappingEnabled = 1;
    u32 toneMapMode = 0;
    f32 exposure = 1.0f;
    f32 toneMapWhitePoint = 4.0f;
    u32 autoExposureEnabled = 0;
    f32 autoExposureTargetLuminance = 0.18f;
    f32 autoExposureMin = 0.25f;
    f32 autoExposureMax = 4.0f;
    f32 autoExposureAdaptation = 1.0f;
    u32 autoExposureHistogramEnabled = 0;
    u32 autoExposureHistoryValid = 0;
    u32 autoExposureFallbacks = 0;
    f32 autoExposureGpuExposure = 1.0f;
    f32 autoExposureGpuTargetExposure = 1.0f;
    f32 autoExposureGpuAverageLuminance = 1.0f;
    u32 colorGradingEnabled = 0;
    f32 colorGradingSaturation = 1.0f;
    f32 colorGradingContrast = 1.0f;
    f32 colorGradingGamma = 1.0f;
    u32 colorGradingLutEnabled = 0;
    u32 colorGradingLutSize = 0;
    f32 colorGradingLutStrength = 0.0f;
    u32 colorGradingLutFallbacks = 0;
    u32 sharpeningEnabled = 0;
    f32 sharpeningStrength = 0.0f;
    f32 sharpeningRadiusPixels = 0.0f;
};

struct RendererBindStats {
    u32 mainMaterialBinds = 0;
    u32 mainMeshBinds = 0;
    u32 gBufferMaterialBinds = 0;
    u32 gBufferMeshBinds = 0;
    u32 mainBonePaletteDescriptorBinds = 0;
    u32 gBufferBonePaletteDescriptorBinds = 0;
    u32 bonePaletteDescriptorBinds = 0;
    u32 gBufferBonePaletteFallbackDescriptorBinds = 0;
    u32 bonePaletteFallbackDescriptorBinds = 0;
    u32 deferredLightingDraws = 0;
    u32 deferredLightingFrameBinds = 0;
    u32 deferredLightingGBufferBinds = 0;
    u32 deferredPbrDebugDraws = 0;
    u32 deferredPbrDebugFrameBinds = 0;
    u32 deferredPbrDebugGBufferBinds = 0;
    u32 hdrCompositeDraws = 0;
    u32 hdrCompositeFrameBinds = 0;
    u32 hdrCompositeTextureBinds = 0;
    u32 gBufferDebugDraws = 0;
    u32 gBufferDebugFrameBinds = 0;
    u32 gBufferDebugTextureBinds = 0;
    u32 deferredShadowDebugDraws = 0;
    u32 deferredShadowDebugFrameBinds = 0;
    u32 deferredShadowDebugTextureBinds = 0;
    u32 shadowCascadeDebugDraws = 0;
    u32 shadowCascadeDebugFrameBinds = 0;
    u32 shadowCascadeDebugTextureBinds = 0;
    u32 localShadowAtlasDebugDraws = 0;
    u32 localShadowAtlasDebugFrameBinds = 0;
    u32 localShadowAtlasDebugTextureBinds = 0;
    u32 localShadowVisibilityDebugDraws = 0;
    u32 localShadowVisibilityDebugFrameBinds = 0;
    u32 localShadowVisibilityDebugTextureBinds = 0;
    u32 localShadowFaceDebugDraws = 0;
    u32 localShadowFaceDebugFrameBinds = 0;
    u32 localShadowFaceDebugTextureBinds = 0;
    u32 contactShadowDebugDraws = 0;
    u32 contactShadowDebugFrameBinds = 0;
    u32 contactShadowDebugGBufferBinds = 0;
    u32 ssaoDebugDraws = 0;
    u32 ssaoDebugFrameBinds = 0;
    u32 ssaoDebugGBufferBinds = 0;
    u32 ssrDebugDraws = 0;
    u32 ssrDebugFrameBinds = 0;
    u32 ssrDebugGBufferBinds = 0;
    u32 ssrHiZBuildDispatches = 0;
    u32 ssrHiZBuildDescriptorBinds = 0;
    u32 ssrHiZConsumerDraws = 0;
    u32 ssrReconstructionTraceDispatches = 0;
    u32 ssrReconstructionTemporalDispatches = 0;
    u32 ssrReconstructionSpatialDispatches = 0;
    u32 ssrReconstructionHistoryCopies = 0;
    u32 reflectionProbeDebugDraws = 0;
    u32 reflectionProbeDebugFrameBinds = 0;
    u32 reflectionProbeDebugGBufferBinds = 0;
    u32 heightFogDebugDraws = 0;
    u32 heightFogDebugFrameBinds = 0;
    u32 heightFogDebugGBufferBinds = 0;
    u32 probeGridDebugDraws = 0;
    u32 probeGridDebugFrameBinds = 0;
    u32 probeGridDebugGBufferBinds = 0;
    u32 probeGridCellDebugDraws = 0;
    u32 probeGridCellDebugFrameBinds = 0;
    u32 probeGridCellDebugGBufferBinds = 0;
    u32 bloomDebugDraws = 0;
    u32 bloomDebugFrameBinds = 0;
    u32 bloomDebugTextureBinds = 0;
    u32 bloomDownsampleDraws = 0;
    u32 bloomDownsampleFrameBinds = 0;
    u32 bloomDownsampleTextureBinds = 0;
    u32 bloomUpsampleDraws = 0;
    u32 bloomUpsampleFrameBinds = 0;
    u32 bloomUpsampleTextureBinds = 0;
    u32 toneMappingDebugDraws = 0;
    u32 toneMappingDebugFrameBinds = 0;
    u32 toneMappingDebugTextureBinds = 0;
    u32 autoExposureDebugDraws = 0;
    u32 autoExposureDebugFrameBinds = 0;
    u32 autoExposureDebugTextureBinds = 0;
    u32 colorGradingDebugDraws = 0;
    u32 colorGradingDebugFrameBinds = 0;
    u32 colorGradingDebugTextureBinds = 0;
    u32 sharpeningDebugDraws = 0;
    u32 sharpeningDebugFrameBinds = 0;
    u32 sharpeningDebugTextureBinds = 0;
    u32 lightTileCullComputeDispatches = 0;
    u32 lightTileCullComputeFrameBinds = 0;
    u32 lightTileCullComputeGroupsX = 0;
    u32 lightTileCullComputeGroupsY = 0;
    u32 autoExposureHistogramDispatches = 0;
    u32 autoExposureHistogramFrameBinds = 0;
    u32 autoExposureHistogramTextureBinds = 0;
    u32 autoExposureHistogramGroupsX = 0;
    u32 autoExposureHistogramGroupsY = 0;
    u32 depthCopyOps = 0;
    u32 depthPrefillDraws = 0;
    u32 depthPrefillMeshBinds = 0;
    u32 weightedTranslucencyClearPasses = 0;
    u32 weightedTranslucencyDraws = 0;
    u32 weightedTranslucencySharedLightListDraws = 0;
    u32 weightedTranslucencyShadowReadyDraws = 0;
    u32 weightedTranslucencyMaterialBinds = 0;
    u32 weightedTranslucencyMeshBinds = 0;
    u32 weightedTranslucencyResolveDraws = 0;
    u32 weightedTranslucencyResolveFrameBinds = 0;
    u32 weightedTranslucencyResolveTextureBinds = 0;
    u32 weightedTranslucencyDebugDraws = 0;
    u32 weightedTranslucencyDebugFrameBinds = 0;
    u32 weightedTranslucencyDebugTextureBinds = 0;
    u32 weightedTranslucencyAlphaReferenceMismatchDraws = 0;
    u32 weightedTranslucencyVelocityDraws = 0;
    u32 weightedTranslucencyVelocityMaterialBinds = 0;
    u32 weightedTranslucencyVelocityMeshBinds = 0;
    u32 dlssMaskDraws = 0;
    u32 dlssMaskWeightedTranslucencyDraws = 0;
    u32 dlssMaskForwardResidualDraws = 0;
    u32 dlssMaskMaterialBinds = 0;
    u32 dlssMaskMeshBinds = 0;
    u32 forwardResidualAlphaReferenceEnabled = 0;
    u32 forwardResidualDraws = 0;
    u32 forwardResidualFrameBinds = 0;
    u32 forwardResidualSharedLightListDraws = 0;
    u32 forwardResidualMaterialBinds = 0;
    u32 forwardResidualMeshBinds = 0;
    u32 forwardResidualVelocityDraws = 0;
    u32 forwardResidualVelocityMaterialBinds = 0;
    u32 forwardResidualVelocityMeshBinds = 0;
    u32 overlayMaterialBinds = 0;
    u32 overlayMeshBinds = 0;
    u32 shadowMeshBinds = 0;
    u32 shadowCascadeAtlasPasses = 0;
    u32 shadowCascadeAtlasDraws = 0;
    u32 shadowCascadeAtlasMeshBinds = 0;
    u32 localShadowAtlasPasses = 0;
    u32 localShadowAtlasDraws = 0;
    u32 localShadowAtlasMeshBinds = 0;
    u32 localShadowResolveEnabled = 0;
    u32 shadowCascadeBufferUpdates = 0;
    u32 localShadowBufferUpdates = 0;
    u32 frameLightConstantUpdates = 0;
    u32 frameLightBufferUpdates = 0;
    u32 frameLightTotalCount = 0;
    u32 frameDirectionalLightCount = 0;
    u32 frameLocalLightCount = 0;
    u32 frameRectLightCount = 0;
    u32 frameLightTileSize = 0;
    u32 frameLightTileCountX = 0;
    u32 frameLightTileCountY = 0;
    u32 frameLightTileCount = 0;
    u32 frameLightTileAssignments = 0;
    u32 frameLightTileAssignmentCapacity = 0;
    u32 frameLightTileOverflowAssignments = 0;
    u32 frameLightTileOverflowCapacity = 0;
    u32 frameLightTileOverflowTiles = 0;
    u32 frameLightTileOverflowDropped = 0;
    u32 frameLightTileAssignmentFallbacks = 0;
    u32 frameLightTileGpuReadbackValid = 0;
    u32 frameLightTileGpuSaturatedTiles = 0;
    u32 frameLightTileGpuMaxCandidates = 0;
    u64 frameLightTileGpuRawCandidates = 0;
    u32 frameLightTileGpuOverflowTiles = 0;
    u32 frameLightTileGpuOverflowDroppedTiles = 0;
    u32 frameLightTileGpuOverflowStored = 0;
    u32 frameLightTileGpuOverflowDropped = 0;
    u32 frameMaterialBufferUpdates = 0;
    u32 frameMaterialCount = 0;
    u32 frameMaterialCapacity = 0;
    u32 frameMaterialOverflowCount = 0;
    u32 frameMaterialOpaqueCount = 0;
    u32 frameMaterialTransparentCount = 0;
    u32 frameMaterialForwardSpecialCount = 0;
    u32 frameMaterialEmissiveHintCount = 0;
    u32 frameMaterialSpecularHintCount = 0;
    u32 frameMaterialSpecularTextureCount = 0;
    u32 frameMaterialAlphaMaskCount = 0;
    u32 frameMaterialAlphaBlendCount = 0;
    u32 frameMaterialUvTransformCount = 0;
    u32 frameMaterialDoubleSidedCount = 0;
    u32 frameMaterialClearcoatCount = 0;
    u32 frameMaterialClearcoatTextureCount = 0;
    u32 frameMaterialClearcoatRoughnessTextureCount = 0;
    u32 frameMaterialTransmissionCount = 0;
    u32 frameMaterialTransmissionTextureCount = 0;
    u32 frameMaterialVolumeCount = 0;
    u32 frameMaterialOpacityTextureCount = 0;
    u32 frameMaterialTexturedCount = 0;
    f32 frameMaterialTextureMipLodBias = 0.0f;
    u32 mainInstancedDraws = 0;
    u32 mainInstancedInstances = 0;
    u32 mainInstanceBufferUploads = 0;
    u32 mainInstanceBufferUploadSkips = 0;
    u32 pushConstantUpdates = 0;
    u64 pushConstantBytes = 0;
};

struct RendererGpuStats {
    bool available = false;
    f32 shadowMs = 0.0f;
    f32 mainMs = 0.0f;
    f32 overlayMs = 0.0f;
    f32 imguiMs = 0.0f;
    f32 totalRecordedMs = 0.0f;
};

enum class RendererTemporalHistoryResetReason : u32 {
    None = 0,
    FirstFrame = 1,
    ExtentChanged = 2,
    MatricesUnavailable = 3,
    Forced = 4
};

enum class RendererTaaFallbackReason : u32 {
    None = 0,
    Disabled = 1,
    CompositeUnavailable = 2,
    HistoryInvalid = 3,
    HistoryColorCold = 4,
    VelocityUnavailable = 5,
    SuppressedForTemporalUpscaler = 6
};

enum class RendererTemporalUpscaleFallbackReason : u32 {
    None = 0,
    Disabled = 1,
    FullResolution = 2,
    InputsUnavailable = 3,
    UpscalerUnavailable = 4,
    DynamicResolutionUnsupported = 5,
    UpscalerEvaluatePathMissing = 6,
    UpscalerEvaluateFailed = 7
};

enum class RendererDlssQualityGateFallbackReason : u32 {
    None = 0,
    NotRequested = 1,
    EvaluateOutputUnavailable = 2,
    CameraMotionVectorsUnavailable = 3,
    ObjectMotionVectorsUnavailable = 4,
    ReactiveMaskUnavailable = 5,
    TransparencyMaskUnavailable = 6,
    ExposurePolicyUnverified = 7,
    PostOrderingUnverified = 8,
    ReferenceBaselineMissing = 9
};

struct RendererTemporalStats {
    u32 antialiasingMode = 0;
    u32 velocityTargetAllocated = 0;
    VkFormat velocityFormat = VK_FORMAT_UNDEFINED;
    u32 velocityCameraMotionEnabled = 0;
    u32 velocityCameraMotionReady = 0;
    u32 velocityObjectMotionReady = 0;
    u32 velocityMaterialAuxTargetAllocated = 0;
    VkFormat velocityMaterialAuxFormat = VK_FORMAT_UNDEFINED;
    u32 velocityMaterialAuxMigrated = 0;
    u32 historyValid = 0;
    u32 historyReset = 0;
    u32 historyResetReason = 0;
    u32 jitterEnabled = 0;
    u32 jitterApplied = 0;
    u32 jitterSequenceIndex = 0;
    f32 jitterPixelsX = 0.0f;
    f32 jitterPixelsY = 0.0f;
    f32 jitterUvX = 0.0f;
    f32 jitterUvY = 0.0f;
    u32 velocityJitteredHistoryPolicy = 0;
    u32 velocityPreviousJitterApplied = 0;
    f32 previousJitterPixelsX = 0.0f;
    f32 previousJitterPixelsY = 0.0f;
    f32 previousJitterUvX = 0.0f;
    f32 previousJitterUvY = 0.0f;
    u32 taaResolveConfigured = 0;
    u32 taaResolveEnabled = 0;
    u32 taaResolveSuppressedForUpscaler = 0;
    u32 taaHistoryColorTargetAllocated = 0;
    VkFormat taaHistoryColorFormat = VK_FORMAT_UNDEFINED;
    u32 taaHistoryColorReady = 0;
    u32 taaHistoryColorCopies = 0;
    f32 taaHistoryWeight = 0.0f;
    u32 taaVelocityReprojectionEnabled = 0;
    u32 taaFallbackReason = 0;
    u32 taaDebugViewEnabled = 0;
    u32 taaRejectionEnabled = 0;
    u32 taaNeighborhoodClampEnabled = 0;
    f32 taaVelocityRejectionThreshold = 0.0f;
    f32 taaDepthRejectionThreshold = 0.0f;
    u32 taaRejectionDebugViewEnabled = 0;
    u32 taaHistoryDebugViewEnabled = 0;
    u32 taaReprojectionDebugViewEnabled = 0;
    u32 temporalConsumerReadinessMask = 0;
    u32 temporalConsumerActiveMask = 0;
    u32 temporalConsumerUnsupportedMask = 0;
    u32 temporalConsumerSsrReady = 0;
    u32 temporalConsumerSsrActive = 0;
    u32 temporalConsumerGtaoReady = 0;
    u32 temporalConsumerMotionBlurReady = 0;
    u32 temporalConsumerDynamicResolutionReady = 0;
    u32 temporalConsumerUpscalerReady = 0;
    f32 renderScaleRequested = 1.0f;
    f32 renderScaleActive = 1.0f;
    u32 renderScaleApplied = 0;
    u32 temporalUpscaleDisplayWidth = 0;
    u32 temporalUpscaleDisplayHeight = 0;
    u32 temporalUpscaleRequestedWidth = 0;
    u32 temporalUpscaleRequestedHeight = 0;
    u32 temporalUpscaleActiveWidth = 0;
    u32 temporalUpscaleActiveHeight = 0;
    u32 temporalUpscaleOutputAllocated = 0;
    VkFormat temporalUpscaleOutputFormat = VK_FORMAT_UNDEFINED;
    u32 temporalUpscaleOutputWidth = 0;
    u32 temporalUpscaleOutputHeight = 0;
    u32 temporalUpscalePostSourceRequested = 0;
    u32 temporalUpscalePostSourceActive = 0;
    u32 temporalUpscalePostSourceFallbackReason = 0;
    u32 dynamicResolutionRequested = 0;
    u32 dynamicResolutionEnabled = 0;
    u32 taauRequested = 0;
    u32 temporalUpscaleRequested = 0;
    u32 temporalUpscaleEnabled = 0;
    u32 temporalUpscaleInputReady = 0;
    u32 temporalUpscaleFallbackReason = 0;
    u32 temporalUpscaleInputReadinessMask = 0;
    u32 temporalUpscaleRequiredInputMask = 0;
    u32 temporalUpscaleContractReady = 0;
    u32 temporalUpscalerPluginRequested = 0;
    u32 temporalUpscalerPluginAvailable = 0;
    u32 temporalUpscalerProviderKind = 0;
    u32 temporalUpscalerPackageFallbackReason = 0;
    u32 temporalUpscalerPackageDirectoryFound = 0;
    u32 temporalUpscalerHeadersFound = 0;
    u32 temporalUpscalerImportLibraryFound = 0;
    u32 temporalUpscalerRuntimeFound = 0;
    u32 temporalUpscalerDlssSuperResolutionSymbolsFound = 0;
    u32 temporalUpscalerDlssFrameGenerationSymbolsFound = 0;
    u32 temporalUpscalerDlssRayReconstructionSymbolsFound = 0;
    u32 temporalUpscalerDlssTransformerPresetSymbolsFound = 0;
    u32 temporalUpscalerSdkVersionMajor = 0;
    u32 temporalUpscalerSdkVersionMinor = 0;
    u32 temporalUpscalerSdkVersionPatch = 0;
    u32 temporalUpscalerPackageReady = 0;
    u32 temporalUpscalerEvaluateAdapterAvailable = 0;
    u32 temporalUpscalerRuntimeFallbackReason = 0;
    u32 temporalUpscalerAdapterCompiled = 0;
    u32 temporalUpscalerInitializationAttempted = 0;
    u32 temporalUpscalerInitialized = 0;
    u32 temporalUpscalerInitializationResult = 0;
    u32 temporalUpscalerCapabilityParametersReady = 0;
    u32 temporalUpscalerCapabilityQueryResult = 0;
    u32 temporalUpscalerFeatureRequirementsQueried = 0;
    u32 temporalUpscalerFeatureRequirementsResult = 0;
    u32 temporalUpscalerFeatureSupportedMask = 0;
    u32 temporalUpscalerFeatureRequirementsSupported = 0;
    u32 temporalUpscalerMinHardwareArchitecture = 0;
    std::string temporalUpscalerMinOsVersion;
    u32 temporalUpscalerInstanceExtensionRequirementsQueried = 0;
    u32 temporalUpscalerInstanceExtensionRequirementsResult = 0;
    u32 temporalUpscalerInstanceExtensionRequirementCount = 0;
    u32 temporalUpscalerInstanceExtensionAvailableCount = 0;
    u32 temporalUpscalerInstanceExtensionMissingAvailableCount = 0;
    u32 temporalUpscalerInstanceExtensionEnabledCount = 0;
    u32 temporalUpscalerInstanceExtensionMissingEnabledCount = 0;
    std::string temporalUpscalerInstanceExtensionRequirements;
    std::string temporalUpscalerInstanceExtensionMissingAvailable;
    std::string temporalUpscalerInstanceExtensionMissingEnabled;
    u32 temporalUpscalerDeviceExtensionRequirementsQueried = 0;
    u32 temporalUpscalerDeviceExtensionRequirementsResult = 0;
    u32 temporalUpscalerDeviceExtensionRequirementCount = 0;
    u32 temporalUpscalerDeviceExtensionAvailableCount = 0;
    u32 temporalUpscalerDeviceExtensionMissingAvailableCount = 0;
    u32 temporalUpscalerDeviceExtensionEnabledCount = 0;
    u32 temporalUpscalerDeviceExtensionMissingEnabledCount = 0;
    std::string temporalUpscalerDeviceExtensionRequirements;
    std::string temporalUpscalerDeviceExtensionMissingAvailable;
    std::string temporalUpscalerDeviceExtensionMissingEnabled;
    u32 temporalUpscalerRuntimeFlavor = 0;
    u32 temporalUpscalerRuntimePathOverridden = 0;
    u32 temporalUpscalerRuntimePathFound = 0;
    std::string temporalUpscalerRuntimePath;
    u32 temporalUpscalerRuntimeDllFound = 0;
    u32 temporalUpscalerRuntimeDllSizeBytes = 0;
    u32 temporalUpscalerRuntimeDllHash = 0;
    u32 temporalUpscalerDlssSuperResolutionSupported = 0;
    u32 temporalUpscalerNeedsUpdatedDriver = 0;
    u32 temporalUpscalerMinDriverVersionMajor = 0;
    u32 temporalUpscalerMinDriverVersionMinor = 0;
    u32 temporalUpscalerFeatureInitResult = 0;
    u32 temporalUpscalerDlssQualityMode = 0;
    u32 temporalUpscalerDlssRecommendedPreset = 0;
    u32 temporalUpscalerOptimalSettingsQueried = 0;
    u32 temporalUpscalerOptimalSettingsResult = 0;
    u32 temporalUpscalerOptimalRenderWidth = 0;
    u32 temporalUpscalerOptimalRenderHeight = 0;
    u32 temporalUpscalerMinRenderWidth = 0;
    u32 temporalUpscalerMinRenderHeight = 0;
    u32 temporalUpscalerMaxRenderWidth = 0;
    u32 temporalUpscalerMaxRenderHeight = 0;
    f32 temporalUpscalerSharpness = 0.0f;
    u32 temporalUpscalerEvaluateRequested = 0;
    u32 temporalUpscalerEvaluateAttempted = 0;
    u32 temporalUpscalerEvaluateFallbackReason = 0;
    u32 temporalUpscalerEvaluateParametersAllocated = 0;
    u32 temporalUpscalerEvaluateParameterAllocationResult = 0;
    u32 temporalUpscalerFeatureCreateAttempted = 0;
    u32 temporalUpscalerFeatureCreated = 0;
    u32 temporalUpscalerFeatureCreateResult = 0;
    u32 temporalUpscalerFeatureRecreated = 0;
    u32 temporalUpscalerFeatureRecreationReason = 0;
    u32 temporalUpscalerDlssEvaluateAttempted = 0;
    u32 temporalUpscalerDlssEvaluateResult = 0;
    u32 temporalUpscalerDlssOutputReady = 0;
    u32 temporalUpscalerDlssRenderWidth = 0;
    u32 temporalUpscalerDlssRenderHeight = 0;
    u32 temporalUpscalerDlssOutputWidth = 0;
    u32 temporalUpscalerDlssOutputHeight = 0;
    u32 temporalUpscalerDlssCreateFlags = 0;
    u32 temporalUpscalerDlssCreateFlagIsHdr = 0;
    u32 temporalUpscalerDlssCreateFlagMvLowRes = 0;
    u32 temporalUpscalerDlssCreateFlagMvJittered = 0;
    u32 temporalUpscalerDlssCreateFlagDepthInverted = 0;
    u32 temporalUpscalerDlssCreateFlagAutoExposure = 0;
    u32 temporalUpscalerDlssInputColorFormat = 0;
    u32 temporalUpscalerDlssInputDepthFormat = 0;
    u32 temporalUpscalerDlssInputMotionVectorFormat = 0;
    u32 temporalUpscalerDlssInputColorWidth = 0;
    u32 temporalUpscalerDlssInputColorHeight = 0;
    u32 temporalUpscalerDlssInputDepthWidth = 0;
    u32 temporalUpscalerDlssInputDepthHeight = 0;
    u32 temporalUpscalerDlssInputMotionVectorWidth = 0;
    u32 temporalUpscalerDlssInputMotionVectorHeight = 0;
    u32 temporalUpscalerDlssInputDepthAspectMask = 0;
    u32 temporalUpscalerDlssInputMotionVectorAspectMask = 0;
    u32 temporalUpscalerDlssInputDepthMatchesRenderExtent = 0;
    u32 temporalUpscalerDlssInputMotionVectorMatchesRenderExtent = 0;
    u32 temporalUpscalerDlssMotionVectorScalePixelSpace = 0;
    u32 temporalUpscalerDlssMotionVectorScaleUnitSpace = 0;
    u32 temporalUpscalerDlssMotionVectorScaleMatchesRenderExtent = 0;
    u32 temporalUpscalerDlssReset = 0;
    f32 temporalUpscalerDlssJitterOffsetX = 0.0f;
    f32 temporalUpscalerDlssJitterOffsetY = 0.0f;
    f32 temporalUpscalerDlssMotionVectorScaleX = 1.0f;
    f32 temporalUpscalerDlssMotionVectorScaleY = 1.0f;
    f32 temporalUpscalerDlssEvaluateSharpness = 0.0f;
    u32 temporalUpscalerDlssQualityGateRequested = 0;
    u32 temporalUpscalerDlssQualityGateReady = 0;
    u32 temporalUpscalerDlssQualityGateFallbackReason = 0;
    u32 temporalUpscalerDlssQualityRequiredMask = 0;
    u32 temporalUpscalerDlssQualityReadyMask = 0;
    u32 temporalUpscalerDlssQualityBlockerMask = 0;
    u32 temporalUpscalerDlssQualityEvaluateOutputReady = 0;
    u32 temporalUpscalerDlssQualityCameraMotionReady = 0;
    u32 temporalUpscalerDlssQualityObjectMotionReady = 0;
    u32 temporalUpscalerDlssQualitySceneContentMotionSupported = 0;
    u32 temporalUpscalerDlssQualityReactiveMaskReady = 0;
    u32 temporalUpscalerDlssQualityTransparencyMaskReady = 0;
    u32 temporalUpscalerDlssQualityExposurePolicyReady = 0;
    u32 temporalUpscalerDlssQualityPostOrderingReady = 0;
    u32 temporalUpscalerDlssQualityReferenceBaselineReady = 0;
};

struct RendererStats {
    RendererCpuStats cpu;
    RendererRenderDebugStats renderDebug;
    RendererDrawStats draw;
    RendererShadowCascadeStats shadowCascades;
    RendererLocalShadowAtlasStats localShadowAtlas;
    RendererWeightedTranslucencyStats weightedTranslucency;
    RendererSsaoStats ssao;
    RendererSsrStats ssr;
    RendererIblStats ibl;
    RendererProbeGridStats probeGrid;
    RendererBonePaletteDrawStats bonePaletteDraw;
    RendererReflectionProbeStats reflectionProbe;
    RendererHeightFogStats heightFog;
    RendererPostProcessStats postProcess;
    RendererBindStats binds;
    RendererGpuStats gpu;
    RendererTemporalStats temporal;
    RenderFrameGraphPlan frameGraph = BuildAAAFrameGraphBlueprint();
};

}
